### ISSUE TITLE
can support chinese language?

### ISSUE THREAD

**Issue by loryrichie** [thecodeholic/lobibox#10]
I want use chinese ,but I don't know how to fix it?

**Comment by thecodeholic** [comment]
There exists a way to do this. It's not so elegant but it exists. You need to override default titles for notifications and messageboxes and override button texts write in whichever language you want.

**Comment by thecodeholic** [comment]
Let me know if you need more help in using chinese language with lobibox

**Comment by loryrichie** [comment]
dear arboshiki:
I have resolved this problem.Thanks
