### ISSUE TITLE
onClick for notifications?

### ISSUE THREAD

**Issue by LCastr0** [thecodeholic/lobibox#11]
Is there a way to use onClick events on notifications?
Like opening a url when clicking that notification

**Comment by thecodeholic** [comment]
Well, there is no direct event in plugin, but plugin initialization returns plugin instance which has `$el` property which refers to jquery object of notification. 

``` javascript
var notify = Lobibox.notify("error", {
    msg: "message"
});

notify.$el.on('click', function(){
    console.log("works");
});
```

**Comment by LCastr0** [comment]
Thanks!

**Comment by thecodeholic** [comment]
Added `onClick` event
