### ISSUE TITLE
Not found sound4.ogg cakephp

### ISSUE THREAD

**Issue by KingOfDragons** [thecodeholic/lobibox#16]
Hi, it always shows me the error 404 http://localhost/cakephp/ecertscsmx/sounds/sound4.ogg.

I create the file and it doesnt work!!!

**Comment by thecodeholic** [comment]
Hi,
Everyday I receive a lot of emails and sometimes I miss some of them.
I have just seen this issue. I hope you fixed the problem.
For the next time you can write me second and third times and I will respond for sure.
Sorry...
