### ISSUE TITLE
delay between 2 messages, 2 notifications

### ISSUE THREAD

**Issue by celtic34fr** [thecodeholic/lobibox#18]
Hello,
I use Lobibox to display all errors back from a form validation. For each notification disappears after the previous, I had to increase the 'delay' value each time.
Would it be possible to set up a delays between the display of each message or notification, to act as if it manages a print queue?

**Comment by thecodeholic** [comment]
Hello,
Thanks for contacting. I have read your message several times but I did not
understand what you mean. Can you explain again?

**Comment by celtic34fr** [comment]
Hello,

it's simple :if I send several notifications at the same time (each by a 
call javascript order), they appear all at the same time (the time lag 
between each due to the processing time is so small, that it sees no).
Is it possible to do that for two consecutive javascript calls to make 
display messages, notifications, there have a time interval (set by 
parameter). We can already set by the parameter 'delay' the display time 
of the message, notification, it would be good to set the time between 
displaying two messages, two notifications.

**Comment by thecodeholic** [comment]
I got what you mean.
This can be achieved using the following way.

``` javascript
Lobibox.notify('warning',{
    // Options
});
// As by default notification delay time is 7000 milliseconds
// Run any code after 7 seconds (when notification remove function is called)
setTimeout(function(){
    //Write your javascript here
    Lobibox.notify('warning',{
        // Options
    });
    //If you change delay option to something else you need to change 7000 to the value you set in delay option
}, 7000);
```

In next update I am going to add before remove and afterRemove events for notification and you can call second notification on afterRemove event of first notification. But right now This can be achieved using the way written above.

Let me know if you need more help.

**Comment by celtic34fr** [comment]
Thank you for your help.
I'll test your recommendation I are to send you my remarks after the tests

**Comment by thecodeholic** [comment]
Added `showAfterPrevious: false` option
