### ISSUE TITLE
when hover the notification ，how to prevent it from closing？？？？

### ISSUE THREAD

**Issue by ExtremeYu** [thecodeholic/lobibox#20]
help！help！help！help！help！help！help！help！help！help！help！help！help！help！help！help！help！help！help！help！help！help！help！help！help！help！help！help！help！help！help！help！help！help！help！help！help！help！help！help！help！help！help！help！help！help！help！help！help！help！help！help！help！help！help！help！help！

**Comment by thecodeholic** [comment]
I have added property `pauseDelayOnHover` which is by default true. So by default notification will not be closed when you mouse over it. If you want to disable this function just give `pauseDelayOnHover: true` and notification will be closed when time is expired. 
Sorry that I haven't fixed this so far. But I have many other things todo.

**Comment by thecodeholic** [comment]
Hi @ExtremeYu,

Did you check if it is fixed?

**Comment by ExtremeYu** [comment]
emm ，i tried to find property pauseDelayOnHover in the file ，but i can’t find it anywhere？where it is？

**Comment by thecodeholic** [comment]
Sorry I forgot to tell you. It is pushed in dev branch

**Comment by ExtremeYu** [comment]
![Uploading 1.png…]()

sorry，can you tell me where the pauseDelayOnHover  it is？
i downloaded dev branch，but i can‘t find pauseDelayOnHover  either。。。。。。。

**Comment by thecodeholic** [comment]
My mistake. It is is master branch not in dev branch.

**Comment by ExtremeYu** [comment]
OK。。now i hover the notification ，the time line will not going on！！！ it’s prefect！

**Comment by thecodeholic** [comment]
Great!!! 
Thanks for good communication
