### ISSUE TITLE
Delay works only if the windows remain focused

### ISSUE THREAD

**Issue by AmirrezaNasiri** [thecodeholic/lobibox#21]
Hello,
`delay`option in Lobibox works only if our focus remain on the page. I mean if we click on other tabs of the browser, delay will stop till we focus again on the windows/tab. It is not a problem by itself but if we use ajax or any other methods with a timer to show notification for example every 15 seconds and set their delays to 10 seconds, we'll face a lot of boxes and it will annoy users.
By the way, your projects are awesome :+1:

**Comment by thecodeholic** [comment]
Hi,
Thanks for liking my plugins.
Added `continueDelayOnInactiveTab` option
