### ISSUE TITLE
When set value to "onClickUrl" then it redirect to the url when click on the close button (top right corner of the notification). 

### ISSUE THREAD

**Issue by webmstz** [thecodeholic/lobibox#24]
Hi,

When set value to "onClickUrl" then it redirect to the url when click on the close button (top right corner of the notification). I will be nice if you could fix this bug.

Thank you.

**Comment by thecodeholic** [comment]
I have already fix this and pushed it on master branch. Please check it out

**Comment by webmstz** [comment]
Thank you. Problem fixed :+1:
