### ISSUE TITLE
Lobibox is dependent upon Bootstrap too, right?

### ISSUE THREAD

**Issue by JamoCA** [thecodeholic/lobibox#3]
If you don't include the Bootstrap library, the icons are not displayed and the width of the pop-up is not consistent.
![lobibox_nobootstrap](https://cloud.githubusercontent.com/assets/1112671/11159130/056f743e-8a12-11e5-8f56-d8262dd38c25.png)

**Comment by thecodeholic** [comment]
Yes lobibox uses bootstrap icons. You can easily disable icons if you do not want

**Comment by JamoCA** [comment]
The description on the project website indicated that the only dependency was jQuery.  I really liked this as I don't use Bootstrap, but found it wasn't true when everything looked broken when Bootstrap wasn't included.

Could you either 1) remove the dependency and include the required styles in a dedicated CSS file or 2) update the project and make it clear that bootstrap is a dependency? (I obviously prefer option #1.)

**Comment by thecodeholic** [comment]
When I started working on the project my wish was the only dependency to be jQuery. I really included bootstrap to make website look nicer. The only problem right now without bootstrap is that it shown ugly right? THIS IS BUG. Every plugin or software has bugs and I am going to fix this bug. I am also going to add default font so to make this plugin independent of bootstrap.

**Comment by JamoCA** [comment]
Awesome!  Thanks.  I don't use Bootstrap in all my projects, but I do use jQuery.  I'd prefer to start using Lobibox to replace two other plugins I'm using (Toastr & SweetAlert).  I prefer your configurable features compared to other plugins.

**Comment by thecodeholic** [comment]
Thank you. I appreciate. I will start working on these issues ASAP, but I will push on `dev` branch. I am also going to optimize code. When every issue will be fixed than I will push it on master branch. You can track changes on `dev` branch if you want.

**Comment by thecodeholic** [comment]
This bug is fixed and it is pushed on dev branch
