### ISSUE TITLE
Font Awesome support?

### ISSUE THREAD

**Issue by JamoCA** [thecodeholic/lobibox#4]
I'm not using Bootstrap in every project. (This seems to a requirement in order to use icons.)

Have you considered adding Font Awesome support so that any of their 585 icons could be used in place of the Bootstrap icon?
http://fontawesome.io/icons/

**Comment by thecodeholic** [comment]
It works fine with Font Awesome icons. You just need to change `iconClass` with font awesome icon

**Comment by JamoCA** [comment]
ok.  Thanks for the information regarding this.  Be default, this plugin is pre-configured and dependent on Bootstrap for many styles.

For use with Font Awesome, I used the following parameters for the various alerts and they look consistent with the Bootstrap icons:
Confirm: `iconClass: 'fa fa-question-circle'`
Alert Error: `iconClass: 'fa fa-times-circle'`
Alert Success: `iconClass: 'fa fa-check-circle'`
Alert Info: `iconClass: 'fa fa-info-circle'`
Alert Warning: `iconClass: 'fa fa-exclamation-circle'`

Maybe a "useFontAwesome" option could be added to automatically set all of these by default.

**Comment by thecodeholic** [comment]
If you want to use icons, Of course you have to include either bootstrap of
font-awesome or any other css file which includes glyphicons. Yes by
default the plugin source file contains bootstrap glyphicons. And
"useFontAwesome" option is also good idea. I will consider this.

**Comment by JamoCA** [comment]
If FontAwesome (or another glyph library) is not used, the only option is to include the entire Bootstrap library so that 5-6 different default icons can be used.  (The Bootstrap library contains a whole lot more than simply icons and some classes may conflict with existing sites that don't use Bootstrap.)

**Comment by thecodeholic** [comment]
Using the following code you can override default icons and write font-awesome icon classes and include font-awesome css file 

``` javascript
Lobibox.alert.DEFAULTS = $.extend({}, Lobibox.alert.DEFAULTS, {
    warning: {
        title: 'Warning',
        iconClass: 'glyphicon glyphicon-question-sign' // Change warning alert icon globally
    },
    info:{
        title: 'Information',
        iconClass: 'glyphicon glyphicon-info-sign'  // Change info alert icon globally
    },
    success: {
        title: 'Success',
        iconClass: 'glyphicon glyphicon-ok-sign'  // Change success alert icon globally
    },
    error: {
        title: 'Error',
        iconClass: 'glyphicon glyphicon-remove-sign'  // Change error alert icon globally
    }
});
```

or you can use bootstrap custom build which contains only glyphicons

http://getbootstrap.com/customize/

**Comment by thecodeholic** [comment]
`iconSource` options is added. Which can be either 'bootstrap' or 'fontAwesome'. By default it is 'bootstrap', but you can set it to 'fontAwesome' in order if you want to use font awesomeIcons. This commit is pushed on dev branch. Soon it will be push on master branch and website documentation will be also updated.
