### ISSUE TITLE
Uncaught (in promise) DOMException

### ISSUE THREAD

**Issue by matmiranda** [thecodeholic/lobibox#43]
Lobibox version: 1.2.7

Follow Code:

```JS
Lobibox.notify('success', {
    sound: true,
    pauseDelayOnHover: true,
    continueDelayOnInactiveTab: false,
    title: 'Title',
    size: 'mini',
    msg: 'message',
    iconSource: "fontAwesome",
    soundPath: '/lib/lobibox/dist/sounds/',
});
```

Sometimes this mistake happens. The sound rings and does not ring. What he did not touch, he made an exception below:

> Uncaught (in promise) DOMException notifications.min.js:1 

![image](https://user-images.githubusercontent.com/24326905/54710225-f652b780-4b25-11e9-8aa2-1b633ca54c8a.png)

**Comment by maszuDEV** [comment]
Hi, Im dealing with same problem. Any progress in this matter?

**Comment by matmiranda** [comment]
No, I'm waiting for the solution.

**Comment by thecodeholic** [comment]
Unfortunately, I could not reproduce this problem.
Can you provide step by step instructions to reproduce it?

**Comment by lixxu** [comment]
seems it's cause of the sound play.
![image](https://user-images.githubusercontent.com/264487/60154176-0bbc3980-9819-11e9-80ad-95d298b38e37.png)

**Comment by lixxu** [comment]
first time is ok, then error occurred if reload
