### ISSUE TITLE
Default Font

### ISSUE THREAD

**Issue by JamoCA** [thecodeholic/lobibox#5]
If Bootstrap isn't used, the font defaults to whatever the browser has for a default. Could you set the default font (in the absence of Bootstrap) to Helvetica,Arial,etc?

**Comment by thecodeholic** [comment]
Right now without bootstrap it is not shown nicely as you show in issue #3 . But later is people ask that they want to use it without bootstrap I will fix the show problem and I will set the default font. Do you want to use it without bootstrap?

**Comment by JamoCA** [comment]
Yes.  Based on your project page, the only dependency was jQuery.  I thought you included Bootstrap so you could make the demo buttons look nice, but I didn't think for a moment that this plugin was also dependent on it.

Would you consider renaming the classes in case optional customization are made to the plugin (so they wouldn't affect Bootstrap)?  Or would you keep everything named the same so that Bootstrap could be easily used?  (I'd hate for any future update of Bootstrap to affect this plugin.  I got stung like this as an early adopter of jQueryUI.)

**Comment by thecodeholic** [comment]
Default font will be added.

**Comment by thecodeholic** [comment]
Default font is added and it is pushed on dev branch
