### ISSUE TITLE
Sounds defaults to /src/sounds/

### ISSUE THREAD

**Issue by JamoCA** [thecodeholic/lobibox#6]
I was trying to figure out why sounds weren't working and it's because the the libraries are hard configured with the path "src/sounds" which won't exist in most cases if only the distribution (dist) files are used.  The .ogg audio files should be copied to the "dist" sub-directory. Is it possible to use a relative path from the "js" sub-directory (ie "../sounds/")?

**Comment by thecodeholic** [comment]
Yes you can use relative path. 
By overriding default options you can set any path you want

``` javascript
Lobibox.notify.DEFAULTS = $.extend({}, Lobibox.notify.DEFAULTS, {
    //override any options from default options
    soundPath: '../sounds/'
});
```

But i will consider this issue and make it so that it will work on both src and dist version

**Comment by JamoCA** [comment]
I understand being able to override them, but I failed to migrate the audio files because they weren't included in the "dist" sub-directory.  My browser developer tools indicated that 404 errors were happening.  I was able to fix this by copying them out of the "src" directory, but if these files are finalized and used by default, they should be included in the "dist" directory too, right?

I think the soundPath parameter is currently required to be an absolute path.  I initially tried a relative path from the included JS file and the path didn't work because the plugin based the web request's path based on the web page's path instead of the script's location.  I use URL rewriting so the path was consistently broken and finally chose to hard-code it to a root path directory (or I'd have to overwrite it on every page.)

**Comment by thecodeholic** [comment]
I have updated plugin two days ago and sounds are already in dist folder.

**Comment by JamoCA** [comment]
Thanks!

(MINOR CONFIG NOTE:  Initially the OGG audio files weren't playing. Firefox Developer won't play the audio file if the proper mime type is not used. I add the missing OGG mime type to IIS. It was hit-and-miss as I checked another IIS server and OGG types were already added.)
