### ISSUE TITLE
"Large" Class = uncloseable

### ISSUE THREAD

**Issue by JamoCA** [thecodeholic/lobibox#7]
When not using bootstrap, the "large sticky notifications" can't be closed manually by clicking the "x".  There's no way to dismiss the notification unless the page is reloaded/refreshed.

**Comment by thecodeholic** [comment]
Once again, It's highly recommended to include bootstrap also in your project. But can you explain more clearly what do you mean? I have tested without bootstrap and they are closed.

**Comment by JamoCA** [comment]
The large notifications are sticky, are not closed automatically and can be closed only by clicking close button.  When Bootstrap is not included, the "x" cannot be clicked on.

Using Firefox Developer tools, the console error that occurs is `TypeError: tabControl.find(...).tab is not a function`.  The little icon "tabs" appear to be broken.  Is a Bootstrap dependency based on the missing icon classes? (BTW, I'm using jQuery 1.11.1)

![lobibox_large](https://cloud.githubusercontent.com/assets/1112671/11191411/fae761a8-8c4f-11e5-96bf-8f4ada7f4132.png)

**Comment by thecodeholic** [comment]
Yes this is also bootstrap dependency problem. This will be fixed also. My advise will be leave these issues opened, track what I push on `dev` branch and see which issues will be fixed. If you will be satisfied, than you can close the issues

**Comment by thecodeholic** [comment]
This problem is also fixed. You can see it on dev branch
