### ISSUE TITLE
Focus on button 

### ISSUE THREAD

**Issue by shethadit** [thecodeholic/lobibox#8]
When click on button, pop up will opened but the key focus is still on the button, so if i press enter or space key another box is pop up. Multiple pop up box is opened.
![focus issue](https://cloud.githubusercontent.com/assets/7188533/11174874/cd66b58e-8c50-11e5-8404-344c63649cf4.png)
Here you can see the 3 box lobibox are created for confirm.

**Comment by thecodeholic** [comment]
Yes I noticed. this will be fixed soon. I will focus on Yes button. Thank you

**Comment by thecodeholic** [comment]
I have updated the plugin. You can see and download new version.

**Comment by shethadit** [comment]
Instead of Yes button , i thing , Create the parameter for default button. If not then focus on first button.

**Comment by thecodeholic** [comment]
It is focused on first button. In the next update I will put the option for
focus button and I will also add navigation by keys.

**Comment by doradora** [comment]
because  default progress didn't have any button,so first button will become "undefined"

**Comment by thecodeholic** [comment]
That's right. I will fix this ASAP.

**Comment by thecodeholic** [comment]
I have fixed the problem. Write If its ok

**Comment by doradora** [comment]
you use jquery to select class ".lobibox-btn"  and then find the firstBtn
It doesn't work with Custom buttons
i think

if (me.$options.buttons){
      var firstBtn = me.$el.find('.lobibox-footer').children();
      firstBtn[0].focus();
 }

**Comment by doradora** [comment]
because my english ability is very poor. 
so I reply very slow

**Comment by thecodeholic** [comment]
Once again you are right. I think your code will work. I will replace it.

**Comment by thecodeholic** [comment]
When messagebox is shown first button takes focus
