### ISSUE TITLE
Adding Bower support

### ISSUE THREAD

**Issue by arcanedev-maroc** [thecodeholic/lobibox#9]
Can you add the bower support ?

Great plugin BTW

**Comment by thecodeholic** [comment]
Thank you for your feedback. I am glad that people like it.
I am going to add bower support but I can not tell you exactly when. Be in touch and watch updates.

**Comment by arcanedev-maroc** [comment]
Take your time :+1:

**Comment by psmarcin** [comment]
+1

**Comment by trestini** [comment]
I think this is already fixed now.

**Comment by thecodeholic** [comment]
Yes I have created package with name "lobibox" and registed on bower

**Comment by arcanedev-maroc** [comment]
I think the `JQuery` dependency is missing in `bower.json`.

Doc about dependencies: https://github.com/bower/spec/blob/master/json.md#dependencies

You can also add the `font-awesome` dependency.
